apiVersion: v1
kind: Service 
metadata:
  name: cicd-svc 
  labels: 
    name: cicd
    env: dev
spec:
  selector:
    name: cicd

  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80

